GET https://dev.lunchmoney.app/v1/transactions HTTP/1.1
Authorization: Bearer {{$dotenv LUNCHMONEY_API_TOKEN}} 

###
# @prompt transactionID
PUT https://dev.lunchmoney.app/v1/transactions/{{transactionID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv LUNCHMONEY_API_TOKEN}}

{
    "transaction": {
        "status":"cleared"
    }
}