name: Test Go
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        go:
          - 1.23
          - 1.22
          - 1.21
          - 1.20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}.x
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...
